export default [
  { name: "All Books" },
  { name: "Editor's Picks" },
  { name: "Academic & Education" },
  { name: "Biography" },
  { name: "Children & Youth" },
  { name: "Fiction & Literature" },
  { name: "Lifestyle" },
  { name: "Politics & Laws" },
  { name: "Science & Research" },
  { name: "Most Popular" },
  { name: "Art" },
  { name: "Business & Career" },
  { name: "Environment" },
  { name: "Health & Fitness" },
  { name: "Personal Growth" },
  { name: "Religion" },
  { name: "Technology" },
];
